name:  Build and Syntax Check 

on: 
  push:
    branches: ["main"] #Commments 
  pull_request: 
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
        #Checkout Repository
        - name: Checkout Code 
        - run: actions/checkout@v4
       # 

       #Set up .NET SDK
        - name: Set up .NET SDK
        - uses: actions/setup-dotnet@v4
          with: 
            dontnet version: '9.0'


      # Restore any dependancies 
        - name: Dependancies
        - run: dotnet restore

      # Run Unit Test
        - name: Unit Test
        - run: dotnet test

      #Build the project
        - name: Project Build 
        - run: dotnet build --configuration release 
      
          
  
