name: Build and Syntax Check

on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'

    - name: Dependencies
      run: dotnet restore

    - name: Unit Test
      run: dotnet test

    - name: Project Build
      run: dotnet build --configuration release 
